### ISSUE TITLE
Oanda Pycharm Forex errors

### ISSUE THREAD

**Issue by Simobill** [blankly-finance/blankly#107]
## Description
Great job. Keep getting errors while using example rsi files.

## RSI.py
from blankly import Oanda, Strategy, StrategyState
#from blankly.utils import trunc
from blankly.indicators import rsi

def init(symbol, state: StrategyState):
    state.variables['history'] = state.interface.history(symbol, 150, resolution=state.resolution, return_as='deque')['close']
    state.variables['own_position'] = False

def price_event(price, symbol, state: StrategyState):
    state.variables['history'].append(price)
    rsi_output = rsi(state.variables['history'])
    print(rsi_output)
    if rsi_output[-1] < 30 and not state.variables['own_position']:
        qty = int(state.interface.cash / price)
        state.interface.market_order(symbol, side='buy', size=qty)
        state.variables['own_position'] = True
    elif rsi_output[-1] > 70 and state.variables['own_position']:
        qty = int(state.interface.account[symbol].available)
        state.interface.market_order(symbol, side='sell', size=qty)
        state.variables['own_position'] = False

exchange = Oanda()
s = Strategy(exchange)
s.add_price_event(price_event, symbol='EUR-USD', resolution='15m', init=init)
results = s.backtest(to='1M')
print(results)

## settings.json
```json
{
  "settings": {
    "account_update_time": 5000,
    "use_sandbox": true,
    "use_sandbox_websockets": false,
    "websocket_buffer_size": 10000,
    "test_connectivity_on_auth": true,

    "coinbase_pro": {
      "cash": "USD"
    },
    "binance": {
      "cash": "USDT",
      "binance_tld": "us"
    },
    "alpaca": {
      "websocket_stream": "iex",
      "cash": "USD",
      "enable_shorting": true
    },
    "oanda": {
      "cash": "USD"
    }
  }
}
```

## backtest.json (if applicable)
```json
{
  "price_data": {
    "assets": []
  },
  "settings": {
    "use_price": "close",
    "smooth_prices": false,
    "GUI_output": true,
    "show_tickers_with_zero_delta": false,
    "save_initial_account_value": true,
    "show_progress_during_backtest": true,
    "cache_location": "./price_caches",
    "continuous_caching": true,
    "resample_account_value_for_metrics": "1d",
    "quote_account_value_in": "USD",
    "ignore_user_exceptions": true,
    "risk_free_return_rate": 0.0
  }
}
```

## Error (if applicable)
```text
#Error with int
Traceback (most recent call last):
  File "C:\..\blankly\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 769, in run
    'state_object'])
  File "C:/../blankly/rsi_bot_old.py", line 20, in price_event
    qty = int(state.interface.account[symbol].available)
KeyError: 'EUR-USD'

```
```text
#Error with trunc with 2 decimals
Traceback (most recent call last):
  File "C:\..\blankly\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 769, in run
    'state_object'])
  File "C:/../blankly/rsi_bot_old.py", line 17, in price_event
    state.interface.market_order(symbol, side='buy', size=qty)
  File "C:\..\blankly\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\paper_trade_interface.py", line 378, in market_order
    ". Try using blankly.trunc(size, decimal_number) to match the exchange resolution.")
blankly.utils.exceptions.InvalidOrder: Size resolution is too high, the highest resolution allowed for this symbol is: 1. You specified 88357.95. Try using blankly.trunc(size, decimal_number) to match the exchange resolution.
Traceback (most recent call last):
  File "C:\..\blankly\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 769, in run
    'state_object'])
  File "C:/../blankly/rsi_bot_old.py", line 17, in price_event
    state.interface.market_order(symbol, side='buy', size=qty)
  File "C:\..\blankly\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\paper_trade_interface.py", line 378, in market_order
    ". Try using blankly.trunc(size, decimal_number) to match the exchange resolution.")
blankly.utils.exceptions.InvalidOrder: Size resolution is too high, the highest resolution allowed for this symbol is: 1. You specified 88361.07. Try using blankly.trunc(size, decimal_number) to match the exchange resolution.
Traceback (most recent call last):
  File "C:\..\blankly\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 769, in run
    'state_object'])
  File "C:/../blankly/rsi_bot_old.py", line 17, in price_event
    state.interface.market_order(symbol, side='buy', size=qty)
  File "C:\..\blankly\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\paper_trade_interface.py", line 378, in market_order
    ". Try using blankly.trunc(size, decimal_number) to match the exchange resolution.")
blankly.utils.exceptions.InvalidOrder: Size resolution is too high, the highest resolution allowed for this symbol is: 1. You specified 88390.75. Try using blankly.trunc(size, decimal_number) to match the exchange resolution.
Traceback (most recent call last):
  File "C:\..\blankly\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 769, in run
    'state_object'])
  File "C:/../blankly/rsi_bot_old.py", line 17, in price_event
    state.interface.market_order(symbol, side='buy', size=qty)
  File "C:\..\blankly\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\paper_trade_interface.py", line 378, in market_order
    ". Try using blankly.trunc(size, decimal_number) to match the exchange resolution.")
blankly.utils.exceptions.InvalidOrder: Size resolution is too high, the highest resolution allowed for this symbol is: 1. You specified 88397.79. Try using blankly.trunc(size, decimal_number) to match the exchange resolution.
...

C:\..\blankly\venv\lib\site-packages\blankly\metrics\portfolio.py:55: RuntimeWarning: invalid value encountered in double_scalars
  return mean / std
C:\..\blankly\venv\lib\site-packages\blankly\metrics\portfolio.py:60: RuntimeWarning: invalid value encountered in double_scalars
  return return_series.mean() * n / abs(max_drawdown(return_series))

```

## Platform Info
 - Python version: 3.7
 - Platform: PyCharm Community Edition 2021.1.3

**Additional context**

**Comment by EmersonDove** [comment]
Looks like we need to add an RSI example specific to OANDA. The easy hot fix here is to use state.base_asset when querying account value. The key error is shown because we have values for accounts like EUR or USD but not for a trading pair like EUR-USD but either component for the pair would work. For other exchanges we have a helper that assumes the base asset if passed a trading pair and we must have missed that here. 

The second error is a bit more confusing because it looks like you're casting to an int. Try making it state.interface.market_order(symbol, 'buy', int(qty)) and do the same for 'sell'

**Comment by Simobill** [comment]
Hello again! Thanx for the quick reply. 
The second error was fixed following your advice. Still no success with first error though. I was hoping for a more thorough hot fix explanation on that (until the RSI example specific to OANDA comes out). 
Also to add to the errors I get an INFO INFO: "benchmark_symbol" not specified in preferences, defaulting to: "None".
Thanx in advnce Emerson

**Comment by EmersonDove** [comment]
Here try this one out:

```python
import blankly


def price_event(price, symbol, state: blankly.StrategyState):
    """ This function will give an updated price every 15 seconds from our definition below """
    state.variables['history'].append(price)
    rsi = blankly.indicators.rsi(state.variables['history'])
    if rsi[-1] < 30 and not state.variables['owns_position']:
        # Dollar cost average buy
        buy = int(state.interface.cash/price)
        state.interface.market_order(symbol, side='buy', size=buy)
        state.variables['owns_position'] = True
    elif rsi[-1] > 70 and state.variables['owns_position']:
        # Dollar cost average sell
        curr_value = state.interface.account[state.base_asset].available
        state.interface.market_order(symbol, side='sell', size=int(curr_value))
        state.variables['owns_position'] = False


def init(symbol, state: blankly.StrategyState):
    # Download price data to give context to the algo
    state.variables['history'] = state.interface.history(symbol, to=150, return_as='deque',
                                                         resolution=state.resolution)['close']
    state.variables['owns_position'] = False


if __name__ == "__main__":
    exchange = blankly.Oanda()

    # Use our strategy helper on coinbase pro
    strategy = blankly.Strategy(exchange)

    # Run the price event function every time we check for a new price - by default that is 15 seconds
    strategy.add_price_event(price_event, symbol='EUR-USD', resolution='1h', init=init)

    # Start the strategy. This will begin each of the price event ticks
    # strategy.start()
    # Or backtest using this
    results = strategy.backtest(to='1y')
    print(results)


```

**Comment by bfan1256** [comment]
Hey @Simobill , did this fix the issue?

**Comment by Simobill** [comment]
Yes issue is solved
