### ISSUE TITLE
Struggling on building from source

### ISSUE THREAD

**Issue by VFermat** [blankly-finance/blankly#113]
## Description
I'm trying to build de package from source using `python3 setup.py install` but I'm getting some problems....
First it did not find Numpy on my virtual environment, so I installed it. Then it could not find Cython. Installed it again.

Now it gives me an error message when running the setup. 

```shell
Traceback (most recent call last):
  File "/Users/vitoreller/Desktop/Projects/open-repos/Blankly/venv/lib/python3.9/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/Users/vitoreller/Desktop/Projects/open-repos/Blankly/venv/lib/python3.9/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/Users/vitoreller/Desktop/Projects/open-repos/Blankly/venv/lib/python3.9/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/Users/vitoreller/Desktop/Projects/open-repos/Blankly/venv/lib/python3.9/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/var/folders/q8/6drbgp5d02zg2z91trgq193c0000gn/T/easy_install-vjxyib74/pandas-1.4.0/setup.py", line 651, in <module>
  File "/var/folders/q8/6drbgp5d02zg2z91trgq193c0000gn/T/easy_install-vjxyib74/pandas-1.4.0/setup.py", line 424, in maybe_cythonize
  File "/Users/vitoreller/Desktop/Projects/open-repos/Blankly/venv/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1079, in cythonize
    pool = multiprocessing.Pool(
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 61, in _launch
    with open(parent_w, 'wb', closefd=False) as f:
  File "/Users/vitoreller/Desktop/Projects/open-repos/Blankly/venv/lib/python3.9/site-packages/setuptools/sandbox.py", line 421, in _open
    if mode not in ('r', 'rt', 'rb', 'rU', 'U') and not self._ok(path):
  File "/Users/vitoreller/Desktop/Projects/open-repos/Blankly/venv/lib/python3.9/site-packages/setuptools/sandbox.py", line 432, in _ok
    realpath = os.path.normcase(os.path.realpath(path))
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/posixpath.py", line 391, in realpath
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not int
```

## Platform Info
 - Python version: 3.9.1
 - Platform: MacOS

**Additional context**
From my experiences on other open-source repositories, I would say that you need a `requirements.txt` file on root, so that users can install it in an easier way when trying to build from source.

Btw, I want to build from source so I can see if I can contribute to your repository! Really loved it!

**Comment by EmersonDove** [comment]
Sure, awesome you're getting it setup and thanks for opening an issue.

I think our install command normally when we do `pip install -e .` to run the setup script.

If that doesn't work I can dig in and try testing the setup on my side.

**Comment by VFermat** [comment]
Amazing! That was able to fix the problem.

Quick question though: wouldn't it be good to have a little walkthrough to contributions? Like a step-by-step process to build from source, patterns to commit messages, branches, etc.?

**Comment by EmersonDove** [comment]
Sure that is a great idea. We have the beginnings of a `contributing.md` but I think it could definitely be updated. 

If you have any ideas about what you want to contribute or want to hear about some projects we're building you could contribute on, feel free to ask.

**Comment by bfan1256** [comment]
Just updated the `contributing.md` to include some of the stuff we talked about here. Will be merged into for the next release :D thanks @VFermat

**Comment by VFermat** [comment]
@bfan1256 amazing!

I'll be closing this issue since @EmersonDove solution worked and you updated the `contributing.md`!
