### ISSUE TITLE
Binance backtesting 

### ISSUE THREAD

**Issue by faycal-rakza** [blankly-finance/blankly#119]
## Description
I have issues when backtesting with Binance api

## settings.json
```json
{
  "settings": {
    "use_sandbox": false,
    "use_sandbox_websockets": false,
    "websocket_buffer_size": 10000,
    "test_connectivity_on_auth": true,

    "coinbase_pro": {
      "cash": "USD"
    },
    "binance": {
      "cash": "USDT",
      "binance_tld": "com"
    },
    "alpaca": {
      "websocket_stream": "iex",
      "cash": "USD",
      "enable_shorting": true,
      "use_yfinance": false
    },
    "oanda": {
      "cash": "USD"
    }
  }
}
```

## backtest.json (if applicable)
```json
{
  "price_data": {
    "assets": []
  },
  "settings": {
    "use_price": "close",
    "smooth_prices": false,
    "GUI_output": true,
    "show_tickers_with_zero_delta": false,
    "save_initial_account_value": true,
    "show_progress_during_backtest": true,
    "cache_location": "./price_caches",
    "continuous_caching": true,
    "resample_account_value_for_metrics": "1d",
    "quote_account_value_in": "USDT",
    "ignore_user_exceptions": true,
    "risk_free_return_rate": 0.0,
    "benchmark_symbol" : null
  }
}
```

## Error (if applicable)
```text
Traceback (most recent call last):
  File "C:\Users\me\PycharmProjects\bot-v2\venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 771, in run
    self.price_events[0]['function'](self.interface.get_price(self.price_events[0]['asset_id']),
  File "C:\Users\me\PycharmProjects\bot-v2\stonks.py", line 20, in price_event
    quantity = int(state.interface.account[symbol].available)
KeyError: 'ALGO-USDT'
```

## Platform Info
 - Python version: 3.9
 - Platform: Windows

**Additional context**
I copied the code in the youtube tutorial

**Comment by EmersonDove** [comment]
Hey thanks for making an issue

When grabbing account values make sure you query either `USDT` or `ALGO`, this is something that under the hood we normally check for but binance doesn't have this particular check. It's a huge we are aware of.

 Change your line to this:
` quantity = int(state.interface.account[state.base_asset].available)`

Where `state.base_asset` will return `ALGO`

**Comment by faycal-rakza** [comment]
Thanks for your reply. I added your code but I steel have issues. The quantity is always 0 when backtesting and I don't know why

```code
from blankly import Binance, Strategy, StrategyState
from blankly.indicators import rsi


def init(symbol, state: StrategyState):
    state.variables['history'] = state.interface.history(symbol, 500, resolution=state.resolution, return_as='deque')[
        'close']
    state.variables['own_position'] = False


def price_event(price, symbol, state: StrategyState):
    state.variables['history'].append(price)
    rsi_output = rsi(state.variables['history'])

    if rsi_output[-1] < 30 and state.variables['own_position'] is False:
        quantity = int(state.interface.account[state.base_asset].available / price)

        print(quantity)

        state.interface.market_order(symbol, 'buy', quantity)
        state.variables['own_position'] = True
    elif rsi_output[-1] > 70 and state.variables['own_position']:
        quantity = int(state.interface.account[state.base_asset].available)
        state.interface.market_order(symbol, 'sell', quantity)
        state.variables['own_position'] = False

        print(quantity)


exchange = Binance()
s = Strategy(exchange)

# No ALGOUSDT in blankly, no chart created
# s.add_price_event(price_event, 'ALGOUSDT', '15m', init=init)

# quantity always 0 (too small)
# s.add_price_event(price_event, 'ALGO-USDT', '15m', init=init)

# no ALGO in Binance API
# s.add_price_event(price_event, 'ALGO', '15m', init=init)

s.add_price_event(price_event, 'ALGO-USDT', '15m', init=init)
results = s.backtest('1y', {'USDT': 1000})
print(results)

# s.start()

```

**Comment by bfan1256** [comment]
Hey @faycal-rakza , it's because you're casting values of the base asset into an integer. This becomes an issue since ALGO is worth more in USD (thus you would get something like 0.25 / 1 which would result in like 0).

In order to fix this, try using `blankly.trunc` which should fix your issue. 

This for the buy: 
```python
quantity = blankly.trunc(state.interface.account[state.base_asset].available / price, 2)
```

This for the sell: 
```python
quantity = blankly.trunc(state.interface.account[state.base_asset].available / price, 2)
```

You can also take a look [here](https://github.com/blankly-finance/examples/blob/main/init/rsi-binance.py)

**Comment by bfan1256** [comment]
Here's the fixed code:

```python
from blankly import Binance, Strategy, StrategyState, trunc
from blankly.indicators import rsi


def init(symbol, state: StrategyState):
    state.variables['history'] = state.interface.history(symbol, 500, resolution=state.resolution, return_as='deque')[
        'close']
    state.variables['own_position'] = False


def price_event(price, symbol, state: StrategyState):
    state.variables['history'].append(price)
    rsi_output = rsi(state.variables['history'])

    if rsi_output[-1] < 30 and state.variables['own_position'] is False:
        quantity = trunc(state.interface.cash / price, 1)

        print(quantity)

        state.interface.market_order(symbol, 'buy', quantity)
        state.variables['own_position'] = True
    elif rsi_output[-1] > 70 and state.variables['own_position']:
        quantity = trunc(state.interface.account[state.base_asset].available, 1)
        state.interface.market_order(symbol, 'sell', quantity)
        state.variables['own_position'] = False

        print(quantity)


exchange = Binance(portfolio_name='Data Key')
s = Strategy(exchange)

# No ALGOUSDT in blankly, no chart created
# s.add_price_event(price_event, 'ALGOUSDT', '15m', init=init)

# quantity always 0 (too small)
s.add_price_event(price_event, 'ALGO-USDT', '15m', init=init)

# no ALGO in Binance API
# s.add_price_event(price_event, 'ALGO', '15m', init=init)

results = s.backtest('1mo', initial_values={'USDT': 1000})
print(results)

# s.start()
```

And output for ya ;) 

![result](https://firebasestorage.googleapis.com/v0/b/blankly-6ada5.appspot.com/o/Screen%20Shot%202022-02-09%20at%2012.54.44%20AM.png?alt=media&token=587d1ce1-ef7e-4f73-9688-6735a17f745b)
