### ISSUE TITLE
Binance - KeyError: 'maxNumOrders'

### ISSUE THREAD

**Issue by rohsat** [blankly-finance/blankly#151]
## Description
The code throws an exception - KeyError: 'maxNumOrders' when running backtests on Binance. 

I think I have found out the root cause of the issue - Binance might have changed their response file. The code worked after I modified  as below. There are other places in the file where filter is fetched in the code using indexes; I feel they need to be modified to fetch data based on the filterType.

## binance_interface.py
```python
       # max_orders = int(filters[6]["maxNumOrders"])
        max_orders = int(next(filter for filter in filters if filter["filterType"] == "MAX_NUM_ORDERS")["maxNumOrders"])
```

## Response
```json
[{'filterType': 'PRICE_FILTER', 'minPrice': '0.01000000', 'maxPrice': '1000000.00000000', 'tickSize': '0.01000000'}, 
{'filterType': 'PERCENT_PRICE', 'multiplierUp': '5', 'multiplierDown': '0.2', 'avgPriceMins': 5}, 
{'filterType': 'LOT_SIZE', 'minQty': '0.00001000', 'maxQty': '9000.00000000', 'stepSize': '0.00001000'}, 
{'filterType': 'MIN_NOTIONAL', 'minNotional': '10.00000000', 'applyToMarket': True, 'avgPriceMins': 5}, 
{'filterType': 'ICEBERG_PARTS', 'limit': 10}, 
{'filterType': 'MARKET_LOT_SIZE', 'minQty': '0.00000000', 'maxQty': '148.34869255', 'stepSize': '0.00000000'}, 
{'filterType': 'TRAILING_DELTA', 'minTrailingAboveDelta': 10, 'maxTrailingAboveDelta': 2000, 'minTrailingBelowDelta': 10, 'maxTrailingBelowDelta': 2000}, 
{'filterType': 'MAX_NUM_ORDERS', 'maxNumOrders': 200}, 
{'filterType': 'MAX_NUM_ALGO_ORDERS', 'maxNumAlgoOrders': 5}]

```

## Error
```
Traceback (most recent call last):
  File "/Users/rohitsathyanathan/Desktop/ML/GitHub/blankly/blankly/exchanges/interfaces/paper_trade/backtest_controller.py", line 771, in run
    self.price_events[0]['function'](self.interface.get_price(self.price_events[0]['asset_id']),
  File "/Users/rohitsathyanathan/Desktop/ML/GitHub/blankly/examples/golden_cross.py", line 36, in price_event
    interface.market_order(symbol, 'buy', int(interface.cash/price))
  File "/Users/rohitsathyanathan/Desktop/ML/GitHub/blankly/blankly/exchanges/interfaces/paper_trade/paper_trade_interface.py", line 359, in market_order
    market_limits = self.get_order_filter(symbol)
  File "/Users/rohitsathyanathan/Desktop/ML/GitHub/blankly/blankly/exchanges/interfaces/paper_trade/paper_trade_interface.py", line 640, in get_order_filter
    self.get_order_filter_cache[symbol] = self.calls.get_order_filter(symbol)
  File "/Users/rohitsathyanathan/Desktop/ML/GitHub/blankly/blankly/exchanges/interfaces/binance/binance_interface.py", line 776, in get_order_filter
    max_orders = int(filters[6]["maxNumOrders"])
KeyError: 'maxNumOrders'
```

## Platform Info
 - Python version: 3.9
 - Platform: MacOS on Apple Silicon

**Comment by EmersonDove** [comment]
Hey @rohsat we have a fix for this on the dev branch and should be releasing it today

**Comment by EmersonDove** [comment]
This should be fixed now, try running `pip install blankly --upgrade`

**Comment by rohsat** [comment]
Hi @EmersonDove  - Thank you. I see the fix.

Suggestion - It might be better to avoid fetching using index values and instead use the filterType to diffuse the ticking time bomb :). I have put in a sample in the issue description above.
