### ISSUE TITLE
Binance: Issue in Golden Cross example

### ISSUE THREAD

**Issue by rohsat** [blankly-finance/blankly#158]
## Description
While backtesting golden_cross.py example in BInance with asset = BTC-USTD, the code was able buy but not sell. 

The code only worked when I modified the below line (as given in rsi.py).

```python
        interface.market_order(symbol, 'sell', int(interface.account[symbol].available))

```
 to

```python
        interface.market_order(symbol, 'sell', state.interface.account[state.base_asset].available)
```

Could you please check why this is happening?

## settings.json
```json
{
  "settings": {
    "use_sandbox_websockets": false,
    "websocket_buffer_size": 10000,
    "test_connectivity_on_auth": true,

    "coinbase_pro": {
      "cash": "USD"
    },
    "binance": {
      "cash": "USDT",
      "binance_tld": "com"
    },
    "alpaca": {
      "websocket_stream": "iex",
      "cash": "USD",
      "enable_shorting": true,
      "use_yfinance": false
    },
    "oanda": {
      "cash": "USD"
    },
    "keyless": {
      "cash": "USD"
    },
    "kucoin": {
      "cash": "USDT"
    },
    "ftx": {
      "cash": "USD"
    }
  }
}
```

## backtest.json 
```json
{
  "price_data": {
    "assets": []
  },
  "settings": {
    "use_price": "close",
    "smooth_prices": false,
    "GUI_output": true,
    "show_tickers_with_zero_delta": false,
    "save_initial_account_value": true,
    "show_progress_during_backtest": true,
    "cache_location": "./price_caches",
    "continuous_caching": true,
    "resample_account_value_for_metrics": "1d",
    "quote_account_value_in": "USDT",
    "ignore_user_exceptions": true,
    "risk_free_return_rate": 0.0,
    "benchmark_symbol" : null
  }
}
```

## Error (got the error multiple times - showing two)
```text
Progress: [#####-----] 47.6% Traceback (most recent call last):
  File "/Users/rohitsathyanathan/Desktop/ML/GitHub/blankly/blankly/exchanges/interfaces/paper_trade/backtest_controller.py", line 771, in run
    self.price_events[0]['function'](self.interface.get_price(self.price_events[0]['asset_id']),
  File "/Users/rs/Desktop/ML/GitHub/blankly/examples/golden_cross.py", line 40, in price_event
    interface.market_order(symbol, 'sell', int(interface.account[symbol].available))
KeyError: 'BTC-USDT'


Progress: [######----] 55.89% Traceback (most recent call last):
  File "/Users/rs/Desktop/ML/GitHub/blankly/blankly/exchanges/interfaces/paper_trade/backtest_controller.py", line 771, in run
    self.price_events[0]['function'](self.interface.get_price(self.price_events[0]['asset_id']),
  File "/Users/rohitsathyanathan/Desktop/ML/GitHub/blankly/examples/golden_cross.py", line 40, in price_event
    interface.market_order(symbol, 'sell', int(interface.account[symbol].available))
KeyError: 'BTC-USDT'
Progress: [##########] 100% Done...

```

## Platform Info
 - Python version: 3.10
 - Platform: MacOS (M1)

**Comment by bfan1256** [comment]
Hey @rohsat, this is indeed correct and we highlight this a little bit in [here](https://docs.blankly.finance/getting-started/common-gotchas#switching-from-alpaca-to-crypto). The issue is because when you store the asset, the asset is stored as `BTC` and not stored as `BTC-USDT`, as a result, we do have to store it and utilize the `interface.account[state.base_asset].available` . You can also take a look at this sample RSI that's found [here](https://github.com/blankly-finance/examples/blob/main/init/rsi_binance.py)
