### ISSUE TITLE
KeyError: 'apiKey' during 'blankly init' | api.generate_keys invalid request

### ISSUE THREAD

**Issue by lsc64** [blankly-finance/blankly#174]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/86673488/168995004-b9220d07-dcf1-4002-b5c2-1ddb9d9a5ed6.png">

```
╰─$ blankly init
? This directory is not empty. Would you like to continue anyways? Yes
? What exchange would you like to connect to? Keyless/No Exchange
? Would you like to connect this model to the Blankly Platform? Yes
? Would you like to create a new model or attach to an existing one? Create new model
? Model name? AI
? Model description?  (Optional)
✔ Created model
✘ An error occurred. Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/blankly/deployment/new_cli.py", line 469, in main
    args.func(args)
  File "/usr/local/lib/python3.10/site-packages/blankly/deployment/new_cli.py", line 163, in blankly_init
    ('blankly.json', generate_blankly_json(api, model, model_type), False),
  File "/usr/local/lib/python3.10/site-packages/blankly/deployment/new_cli.py", line 268, in generate_blankly_json
    data['api_key'] = keys['apiKey']
KeyError: 'apiKey'
```

Tracing this error back leads to api.generate keys
```
def generate_keys(self, project_id: str):
        return self.__request('post', 'project/generate-project-token',
                              data={'projectId': project_id)
```
which returns
`{'error': 'Missing required argument: name'}`

A 'fix' it we want to call it that is adding the required arguments `name` and  `autogenerated`

```
 def generate_keys(self, project_id: str):
     return self.__request('post', 'project/generate-project-token',
                           data={'projectId': project_id, 'name': 'test', 'autogenerated': True})
```

I have no idea what these arguments mean and where they're supposed to come from, but they need to be added there.

**Comment by lsc64** [comment]
> Hey sorry this is should be resolved in this most recent update (just released).
> 
> Try doing `pip install blankly --upgrade`.
> 
> Nice digging btw that helped me know the error immediately.

Glad I could help and it is indeed fixed for me.
