### ISSUE TITLE
Binance futures not working

### ISSUE THREAD

**Issue by choesy** [blankly-finance/blankly#230]
## Description

The simple futures example is not working. I found the example in the finance docs: 
[blankly docs](https://docs.blankly.finance/futures/getting-started)

I tried to live trad just to obtain prices. But it looks like that the "state" variable is wrong type when passed into callback functions.
It should have been FuturesStrategyLogger instead of StrategyLogger.

## settings.json
```json

{
    "settings": {
        "use_sandbox_websockets": false,
        "websocket_buffer_size": 10000,
        "test_connectivity_on_auth": true,
        "auto_truncate": false,
        "global_shorting": false,
        "simulate_margin": true,
        "coinbase_pro": {
            "cash": "USD"
        },
        "binance": {
            "cash": "USDT",
            "binance_tld": "com"
        },
        "binance_futures": {
            "cash": "USDT",
            "margin_type": "USDT-M"
        },
        "alpaca": {
            "websocket_stream": "iex",
            "cash": "USD",
            "enable_shorting": true,
            "use_yfinance": false
        },
        "oanda": {
            "cash": "USD"
        },
        "okx": {
            "cash": "USDT"
        },
        "keyless": {
            "cash": "USD"
        },
        "kucoin": {
            "cash": "USDT"
        },
        "ftx": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "ftx_futures": {
            "cash": "USD",
            "ftx_tld": "com"
        },
        "paper": {
            "price_source": "api"
        }
    }
}

```

## backtest.json (if applicable)
```json

{
    "price_data": {
        "assets": []
    },
    "settings": {
        "use_price": "close",
        "smooth_prices": false,
        "GUI_output": true,
        "show_tickers_with_zero_delta": false,
        "save_initial_account_value": true,
        "show_progress_during_backtest": true,
        "cache_location": "./price_caches",
        "continuous_caching": true,
        "resample_account_value_for_metrics": "1d",
        "quote_account_value_in": "USDT",
        "ignore_user_exceptions": true,
        "risk_free_return_rate": 0.0,
        "benchmark_symbol": null
    }
}

```

## Error (if applicable)
```text

Exception in thread Thread-1 (main):
Traceback (most recent call last):
  File "C:\Users\aleks\.pyenv\pyenv-win\versions\3.10.9\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\aleks\.pyenv\pyenv-win\versions\3.10.9\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 159, in main
    self.run_live()
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 191, in run_live
    self.__run_init()
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 183, in __run_init
    kwargs['init'](kwargs['symbol'], kwargs['state'])
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\bot.py", line 27, in init
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\futures\utils.py", line 13, in close_position
    position = state.interface.get_position(symbol)
AttributeError: 'StrategyLogger' object has no attribute 'get_position'

```

## Platform Info
 - Python version: 3.10.9
 - Platform: Windows 10

**Comment by choesy** [comment]
I also have a problem, when i try to backtest i get an error:

```text

No cached data found for BTC-USDT from: 1646160556.8444185 to 1677610156.8444185 at a resolution of 86400 seconds.
Traceback (most recent call last):
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 863, in run
    self.interface.receive_price(frame_symbol, frame[0][use_price])
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\numpy\core\records.py", line 509, in __getitem__
    obj = super().__getitem__(indx)
IndexError: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\bot.py", line 43, in <module>
    strategy.backtest(to='1y', initial_values={'USDT': 10000})
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 323, in backtest
    res = self.model.backtest(args={}, initial_values=initial_values, settings_path=settings_path, kwargs=kwargs)
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\model\model.py", line 64, in backtest
    backtest = self.__backtester.run(args,
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 878, in run
    raise IndexError('No cached or downloaded data available. Try adding arguments such as to="1y" '
IndexError: No cached or downloaded data available. Try adding arguments such as to="1y" in the backtest command. If there should be data downloaded, try deleting your ./price_caches folder. Also ensure that "BTC-USDT" is spelled correctly.


```

**Comment by EmersonDove** [comment]
Can you attach the example code you're running?

**Comment by choesy** [comment]
It is pretty basic code:

```python

import blankly
from blankly import futures, Side
from blankly.futures import FuturesStrategyState
from blankly.futures.utils import close_position


def price_event(price, symbol, state: FuturesStrategyState):
    prev_price = state.variables['prev_price']
    position = state.interface.get_position(symbol)

    # if the price rose more than 1,000 and we don't already have a short position, then short sell
    if not position and price - prev_price >= 1000:
        order_size = (state.interface.cash / price) * 0.99
        state.interface.market_order(symbol, Side.SELL, order_size)

    # if the price stablized and we *do* have a short position, close our position.
    elif position and abs(price - prev_price) <= 100:
        # we use abs(position['size']) here because position['size'] can (and will) be negative, since we have taken a short position.
        state.interface.market_order(symbol, Side.BUY, abs(position['size']), reduce_only=True)

    state.variables['prev_price'] = price


# This function will be run before our algorithm starts
def init(symbol, state: FuturesStrategyState):
    # Close any open positions
    close_position(symbol, state)

    # Give the algo the previous price as context
    last_price = state.interface.history(symbol, to=1, return_as='deque', resolution=state.resolution)['close'][-1]
    state.variables['prev_price'] = last_price


if __name__ == "__main__":
    exchange = futures.BinanceFutures("futuretest")
    strategy = futures.FuturesStrategy(exchange)

    strategy.add_price_event(price_event, init=init, teardown=close_position, symbol='BTC-USDT', resolution='1h')
    strategy.backtest(to='30d', initial_values={'USDT': 10000})

```

but when i run it now i get different error, i have no idea what changed, sorry.

```text
INFO: Live futures trading is untested due to US relations - this prevents blankly developers from integrating with these exchanges. We are looking for someone who is interested in helping us create & test our integrations.
INFO: Live futures trading is untested due to US relations - this prevents blankly developers from integrating with these exchanges. We are looking for someone who is interested in helping us create & test our integrations.
No cached data found for BTC-USDT from: 1675158932.9992757 to 1677610340 at a resolution of 3600 seconds.

Backtesting...
Traceback (most recent call last):
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 938, in run
    self.model.main(args)
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 157, in main
    self.run_backtest()
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 167, in run_backtest
    self.__run_init()
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 183, in __run_init
    kwargs['init'](kwargs['symbol'], kwargs['state'])
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\bot.py", line 30, in init
    last_price = state.interface.history(symbol, to=1, return_as='deque', resolution=state.resolution)['close'][-1]
IndexError: deque index out of range
```

**Comment by EmersonDove** [comment]
It looks like in your `init` function when you're asking for the last bar with `to=1`, it ends up not finding any bar, then the `[-1]` throws an index error, try turning `to=1` to something larger like `to=100`.

**Comment by choesy** [comment]
Actually there are two sets of problems now that I inspected. The first one occurs when I try to preform a backtest on futures.
Code in both cases:
```python

import blankly
from blankly import futures, Side
from blankly.futures import FuturesStrategyState
from blankly.futures.utils import close_position


def price_event(price, symbol, state: FuturesStrategyState):
    prev_price = state.variables['prev_price']
    position = state.interface.get_position(symbol)

    # if the price rose more than 1,000 and we don't already have a short position, then short sell
    if not position and price - prev_price >= 1000:
        order_size = (state.interface.cash / price) * 0.99
        state.interface.market_order(symbol, Side.SELL, order_size)

    # if the price stablized and we *do* have a short position, close our position.
    elif position and abs(price - prev_price) <= 100:
        # we use abs(position['size']) here because position['size'] can (and will) be negative, since we have taken a short position.
        state.interface.market_order(symbol, Side.BUY, abs(position['size']), reduce_only=True)

    state.variables['prev_price'] = price


# This function will be run before our algorithm starts
def init(symbol, state: FuturesStrategyState):
    # Close any open positions
    close_position(symbol, state)

    # Give the algo the previous price as context
    last_price = state.interface.history(symbol, to=100, return_as='deque', resolution=state.resolution)['close'][-1]
    state.variables['prev_price'] = last_price


if __name__ == "__main__":
    exchange = futures.BinanceFutures("futuretest")
    strategy = futures.FuturesStrategy(exchange)

    strategy.add_price_event(price_event, init=init, teardown=close_position, symbol='BTC-USDT', resolution='1d')

    #strategy.start()
    strategy.backtest(to="1y", initial_values={'USDT': 10000})

```

The error i get when i have strategy.start() commented out and backtest enabled:

```text

INFO: Live futures trading is untested due to US relations - this prevents blankly developers from integrating with these exchanges. We are looking for someone who is interested in helping us create & test our integrations.
INFO: Live futures trading is untested due to US relations - this prevents blankly developers from integrating with these exchanges. We are looking for someone who is interested in helping us create & test our integrations.
No cached data found for BTC-USDT from: 1646241973.536196 to 1677691573.536196 at a resolution of 86400 seconds.

Backtesting...
Traceback (most recent call last):
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\exchanges\interfaces\paper_trade\backtest_controller.py", line 938, in run
    self.model.main(args)
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 157, in main
    self.run_backtest()
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 167, in run_backtest
    self.__run_init()
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 183, in __run_init
    kwargs['init'](kwargs['symbol'], kwargs['state'])
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\bot.py", line 30, in init
    last_price = state.interface.history(symbol, to=100, return_as='deque', resolution=state.resolution)['close'][-1]
IndexError: deque index out of range

```

and when i try the live trading on futures testnet by commenting the backtest and uncommenting the start():

```text

INFO: Live futures trading is untested due to US relations - this prevents blankly developers from integrating with these exchanges. We are looking for someone who is interested in helping us create & test our integrations.
Exception in thread Thread-1 (main):
Traceback (most recent call last):
  File "C:\Users\aleks\.pyenv\pyenv-win\versions\3.10.9\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\aleks\.pyenv\pyenv-win\versions\3.10.9\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 159, in main
    self.run_live()
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 194, in run_live
    self.__run_init()
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\frameworks\strategy\strategy.py", line 183, in __run_init
    kwargs['init'](kwargs['symbol'], kwargs['state'])
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\bot.py", line 27, in init
    close_position(symbol, state)
  File "C:\Users\aleks\Desktop\Projects\quant-macd-trade-bot\.venv\lib\site-packages\blankly\futures\utils.py", line 13, in close_position
    position = state.interface.get_position(symbol)
AttributeError: 'StrategyLogger' object has no attribute 'get_position'

```
For the first case i have printed out the "state.interface.history(symbol, to=100, return_as='deque', resolution=state.resolution)" returns no data. I don't know if this is specific to futures testnet problem or blankly bug.

In the second case, when trying to "live trade" it seems like StrategyLogger type of object is being passed to callback functions instead of FuturesStrategyLogger that contains "get_position". I checked it and confirmed it with print(type(state)) inside init function. The same goes for the first case with backtrading (StrategyLogger instead of FuturesStrategyLogger).

**Comment by choesy** [comment]
Just an update:
When I downloaded blankly directly from github and installed it with "pip install -e .", The interface.history started to return data ( not consistently, depending on a run, sometimes it returned 5 candles, sometimes 10 ... ). I am still using futures testnet api keys.
The error  "AttributeError: 'StrategyLogger' object has no attribute 'get_position'" still persists, but I believe there is a a temporary workaround for now by using functions that exist both in StrategyLogger and FuturesStrategyLogger.
