### ISSUE TITLE
Try toggling the 'use_sandbox' setting in your settings.json or check if the keys were input correctly into your keys.json.

### ISSUE THREAD

**Issue by MislavSag** [blankly-finance/blankly#74]
## Description
I am trying to run sample code from docs using Alpaca paper trading account:
```
from blankly import Strategy, StrategyState, Interface
from blankly import Alpaca
from blankly.indicators import rsi


def init(symbol, state: StrategyState):
    # Download price data to give context to the algo
    state.variables['history'] = state.interface.history(symbol, to='1y', return_as='list')['close']

def price_event(price, symbol, state: StrategyState):
    # we'll come back to this soon
    print("New price event: " + str(price) + ".")
    pass


alpaca = Alpaca()
s = Strategy(alpaca)
s.add_price_event(price_event, 'MSFT', resolution='1m', init=init)
s.start()
```
but I a getting an error below.

## settings.json
```python
{
    "settings": {
      "account_update_time": 5000,
      "use_sandbox": false,
      "use_sandbox_websockets": false,
      "websocket_buffer_size": 10000,
      "test_connectivity_on_auth": true,
  
      "coinbase_pro": {
        "cash": "USD"
      },
      "binance": {
        "cash": "USDT",
        "binance_tld": "us"
      },
      "alpaca": {
        "websocket_stream": "iex",
        "cash": "USD"
      }
    }
  }
```

## Error (if applicable)
```python
INFO: No portfolio name to load specified, defaulting to the first in the file: (another cool portfolio). This is fine if there is only one portfolio in use.
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\alpaca_trade_api\rest.py", line 208, in _one_request
    resp.raise_for_status()
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\requests\models.py", line 953, in raise_for_status  
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.alpaca.markets/v2/account        

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\blankly\exchanges\interfaces\alpaca\alpaca_interface.py", line 48, in init_exchange
    account_info = self.calls.get_account()
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\alpaca_trade_api\rest.py", line 246, in get_account
    resp = self.get('/account')
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\alpaca_trade_api\rest.py", line 224, in get
    return self._request('GET', path, data)
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\alpaca_trade_api\rest.py", line 187, in _request
    return self._one_request(method, url, opts, retry)
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\alpaca_trade_api\rest.py", line 216, in _one_request
    raise APIError(error, http_error)
alpaca_trade_api.rest.APIError: request is not authorized

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mislav\Documents\blankly_projects\intro.py", line 16, in <module>
    alpaca = Alpaca()
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\blankly\exchanges\interfaces\alpaca\alpaca.py", line 26, in __init__
    Exchange.__init__(self, 'alpaca', portfolio_name, keys_path, settings_path)
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\blankly\exchanges\exchange.py", line 41, in __init__
    self.calls, self.interface = self.__direct_calls_factory.create(self.__type, self.__auth, preferences_path)
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\blankly\exchanges\interfaces\direct_calls_factory.py", line 57, in create
    return calls, AlpacaInterface(calls, preferences_path)
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\blankly\exchanges\interfaces\alpaca\alpaca_interface.py", line 43, in __init__
    super().__init__('alpaca', authenticated_API, preferences_path, valid_resolutions=[60, 60*5, 60*15, 60*60*24])
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\blankly\exchanges\interfaces\exchange_interface.py", line 49, in __init__
    self.init_exchange()
  File "C:\ProgramData\Anaconda3\envs\blankly\lib\site-packages\blankly\exchanges\interfaces\alpaca\alpaca_interface.py", line 50, in init_exchange
    raise APIException(e.__str__() + ". Are you trying to use your normal exchange keys "
blankly.utils.exceptions.APIException: request is not authorized. Are you trying to use your normal exchange keys while in sandbox mode?
Try toggling the 'use_sandbox' setting in your settings.json or check if the keys were input correctly into your keys.json.
```

## Platform Info
 - Python version: 3.9
 - Platform: Windows

**Comment by EmersonDove** [comment]
Hey thanks for asking!

In your settings.json that you attached:

```json
{
    "settings": {
      "account_update_time": 5000,
      "use_sandbox": false,
      "use_sandbox_websockets": false,
      "websocket_buffer_size": 10000,
      "test_connectivity_on_auth": true,
  
      "coinbase_pro": {
        "cash": "USD"
      },
      "binance": {
        "cash": "USDT",
        "binance_tld": "us"
      },
      "alpaca": {
        "websocket_stream": "iex",
        "cash": "USD"
      }
    }
  }
```

Just change the `"use_sandbox": false` to `"use_sandbox": true`
